### ISSUE TITLE
Error analyzing pops_04g.prx (ofw 6.61)

### ISSUE THREAD

**Issue by sajattack** [pspdev/psp-ghidra-scripts#14]
```
SonyPSPResolveNIDs.py> Running...
Parsing pspsdk_types.h...
WARN: Failed to parse typedef struct PspIoDrvFileArg
WARN: Failed to parse typedef struct PspIoDrvFuncs
WARN: Failed to parse typedef struct PspIoDrv
WARN: Failed to parse typedef struct PspSysEventHandler{
WARN: Failed to parse typedef int (*PspHttpPasswordCB)(
WARN: Failed to parse typedef struct SceIoDirent {
WARN: Failed to parse typedef struct _pspUtilityGameSharingParams
WARN: Failed to parse typedef struct _pspUtilityMsgDialogParams
WARN: Failed to parse typedef struct SceUtilitySavedataParam
PSPSDKTypes parsed in 0.250999927521 seconds
Could not find .rodata.sceModuleInfo section, calculating its location from ELF Program Headers
Resolving Export NIDs for pops
Traceback (most recent call last):
  File "/home/paul/projects/psp/psp-ghidra-scripts/SonyPSPResolveNIDs.py", line 524, in <module>
    main()
  File "/home/paul/projects/psp/psp-ghidra-scripts/SonyPSPResolveNIDs.py", line 520, in main
    resolveExports(exports_addr, exports_end, nidDB, module_name)
  File "/home/paul/projects/psp/psp-ghidra-scripts/SonyPSPResolveNIDs.py", line 307, in resolveExports
    stub_addr = getDataAt(stub_base.add(4*num_funcs + 4*var_idx)).value
AttributeError: 'NoneType' object has no attribute 'value'
SonyPSPResolveNIDs.py> Finished!
```

**Comment by hrydgard** [comment]
Similar with PSMF libraries from games. 

The issue seems to be in the ELF import step, where Ghidra discards some segments as invalid.

**Comment by hrydgard** [comment]
Actually, I take that back about PSMF, that was me doing a bad job of dumping the decrypted files from PPSSPP.

However, some firmware modules will still not parse properly with this script. 

* mp4msv.prx
* some others I don't remember now...

**Comment by kotcrab** [comment]
Copy pasting possible fix from Discord (original [here](https://discord.com/channels/479828644970364928/728206969294553110/1374450013215658025) by Cat):

```
diff --git a/SonyPSPResolveNIDs.py b/SonyPSPResolveNIDs.py
index fc49e44..6274932 100644
--- a/SonyPSPResolveNIDs.py
+++ b/SonyPSPResolveNIDs.py
@@ -155,7 +155,10 @@ def resolveExports(exports_addr, exports_end, nidDB, moduleInfo_name):
         module_name = "(none)"
         # why we can't just get a number to compare against 0 is beyond me
         if module_name_addr.value.toString() != "00000000":
-            module_name = getDataAt(module_name_addr.value).value
+            if getDataAt(module_name_addr.value):
+                module_name = getDataAt(module_name_addr.value).value
+            else:
+                module_name = "unknown"
         elif module_index == 0:
             module_name = moduleInfo_name
         else:
```
